# Generated by Django 4.1.1 on 2022-10-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
